export const TABLE_RESIZE = 'TABLE_RESIZE'

export const TABLE_RESIZE_REMOVE = 'TABLE_RESIZE_REMOVE_COL'

export const TABLE_CELL_DATA = 'TABLE_CELL_DATA'

export const CHANGE_CURRENT_CELL = 'CHANGE_CURRENT'

export const CHANGE_FORMULA_TEXT = 'CHANGE_FORMULA_TEXT'

export const APPLY_STYLE = 'APPLY_STYLE'

export const CHANGE_EXCEL_TITLE = 'CHANGE_EXCEL_TITLE'
